#pragma once

Q_DECL_CONSTEXPR static const int VRT_VERSION_1  =  1;	// Original version
Q_DECL_CONSTEXPR static const int VRT_VERSION_2  =  2;	// Added ability to show IC pin numbers
Q_DECL_CONSTEXPR static const int VRT_VERSION_3  =  3;	// Added ground fill parameters
Q_DECL_CONSTEXPR static const int VRT_VERSION_4  =  4;	// Simplified mapping of pinChar to pinIndex
Q_DECL_CONSTEXPR static const int VRT_VERSION_5  =  5;	// Added flag to show grid
Q_DECL_CONSTEXPR static const int VRT_VERSION_6  =  6;	// Added color saturation
Q_DECL_CONSTEXPR static const int VRT_VERSION_7  =  7;	// Added pin labels
Q_DECL_CONSTEXPR static const int VRT_VERSION_8  =  8;	// Added crystal component type
Q_DECL_CONSTEXPR static const int VRT_VERSION_9  =  9;	// Added more trimmers/relays/switches
Q_DECL_CONSTEXPR static const int VRT_VERSION_10 = 10;	// Added rectangles
Q_DECL_CONSTEXPR static const int VRT_VERSION_11 = 11;	// Added component manager, bounding rects, reworked Footprint class
Q_DECL_CONSTEXPR static const int VRT_VERSION_12 = 12;	// Added horizontal vero strips
Q_DECL_CONSTEXPR static const int VRT_VERSION_13 = 13;	// Added crop margin
Q_DECL_CONSTEXPR static const int VRT_VERSION_14 = 14;	// Added text manager
Q_DECL_CONSTEXPR static const int VRT_VERSION_15 = 15;	// Added text color
Q_DECL_CONSTEXPR static const int VRT_VERSION_16 = 16;	// Added more components
Q_DECL_CONSTEXPR static const int VRT_VERSION_17 = 17;	// Added text sizes for components and pins
Q_DECL_CONSTEXPR static const int VRT_VERSION_18 = 18;	// Added custom component type and shapes class
Q_DECL_CONSTEXPR static const int VRT_VERSION_19 = 19;	// Added component editor flag and new component attributes
Q_DECL_CONSTEXPR static const int VRT_VERSION_20 = 20;	// Added SURFACE_HOLE attribute
Q_DECL_CONSTEXPR static const int VRT_VERSION_21 = 21;	// Added target board size
Q_DECL_CONSTEXPR static const int VRT_VERSION_22 = 22;	// Label offsets measured in 1/16th of a square instead of 1/4
Q_DECL_CONSTEXPR static const int VRT_VERSION_23 = 23;	// Added component definer
Q_DECL_CONSTEXPR static const int VRT_VERSION_24 = 24;	// Added routing method parameter
Q_DECL_CONSTEXPR static const int VRT_VERSION_25 = 25;	// Moves some variables from CompElement to Element
Q_DECL_CONSTEXPR static const int VRT_VERSION_26 = 26;	// Reworked codes in Pin to allow 2 wires per grid point
Q_DECL_CONSTEXPR static const int VRT_VERSION_27 = 27;	// Modified Element to store additional wire info
Q_DECL_CONSTEXPR static const int VRT_VERSION_28 = 28;	// Added options for wires to share holes or cross/overlay
Q_DECL_CONSTEXPR static const int VRT_VERSION_29 = 29;	// Added color to component definition
Q_DECL_CONSTEXPR static const int VRT_VERSION_30 = 30;	// Added pin label alignment
Q_DECL_CONSTEXPR static const int VRT_VERSION_31 = 31;	// New treatment of labels under part rotation and centering.
Q_DECL_CONSTEXPR static const int VRT_VERSION_32 = 32;	// Added size of solder mask and silk screen pen
Q_DECL_CONSTEXPR static const int VRT_VERSION_33 = 33;	// Added PCB track mode, board edge margin, PTH/NPTH option
Q_DECL_CONSTEXPR static const int VRT_VERSION_34 = 34;	// Added 3rd dimension to grid, and display layer
Q_DECL_CONSTEXPR static const int VRT_VERSION_35 = 35;	// Added via dimensions
Q_DECL_CONSTEXPR static const int VRT_VERSION_36 = 36;	// Added thin tracks style
Q_DECL_CONSTEXPR static const int VRT_VERSION_37 = 37;	// Added flag to enable/disable vias
Q_DECL_CONSTEXPR static const int VRT_VERSION_38 = 38;	// Added Bourns 3362 series trimpots
Q_DECL_CONSTEXPR static const int VRT_VERSION_39 = 39;	// Added custom pin/hole size on components
Q_DECL_CONSTEXPR static const int VRT_VERSION_40 = 40;	// Allow 50 mil holes, and fix bug with non-wire hole use
Q_DECL_CONSTEXPR static const int VRT_VERSION_41 = 41;	// Allow user-specified colors for nodes
Q_DECL_CONSTEXPR static const int VRT_VERSION_42 = 42;	// Auto-fix corruption of old VRTs on load
Q_DECL_CONSTEXPR static const int VRT_VERSION_43 = 43;	// Added vero numbers and vero letters
Q_DECL_CONSTEXPR static const int VRT_VERSION_44 = 44;	// Added option to show close tracks
Q_DECL_CONSTEXPR static const int VRT_VERSION_45 = 45;	// Added layer preference for each component pin
Q_DECL_CONSTEXPR static const int VRT_VERSION_46 = 46;	// Added pad offsets for PCB mode
Q_DECL_CONSTEXPR static const int VRT_VERSION_47 = 47;	// Added component attribute to allow flying wires
Q_DECL_CONSTEXPR static const int VRT_VERSION_48 = 48;	// Added board setting to show/hide flying wires
Q_DECL_CONSTEXPR static const int VRT_VERSION_49 = 49;	// Added vertical alignment flag to text boxes
Q_DECL_CONSTEXPR static const int VRT_VERSION_50 = 50;	// Added background color property
Q_DECL_CONSTEXPR static const int VRT_VERSION_51 = 51;	// Added pinlabels to component editor
Q_DECL_CONSTEXPR static const int VRT_VERSION_52 = 52;	// Added thermal relief tag size
Q_DECL_CONSTEXPR static const int VRT_VERSION_53 = 53;	// Added X-thermals flag
Q_DECL_CONSTEXPR static const int VRT_VERSION_CURRENT = VRT_VERSION_53;
